#!/usr/bin/env bash

shopt -s nullglob globstar

shift $(expr $OPTIND - 1 )

[[ $1 = "--" ]] && shift
prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | rofi -dmenu -window-title "Password name")

[[ -n $password ]] || exit

if [[ $password == *"otp"* ]]; then
    pass otp "$password" | head -n1 | wl-copy --paste-once 2>/dev/null
else
    pass show "$password" | head -n1 | wl-copy --paste-once 2>/dev/null
fi

if [[ $? != 0 ]]; then
	echo "Some error has occured"
else
	echo "Password copyied to clipboard"
fi
